Домашняя работа 2
loveandpepper/edu_application pull request #2
Opened 2024-12-22 12:14 UTC by loveandpepper

новый алгоритм равномерного распределения (import even [число] [путь]), сохранение вместо вывода через save, импорт из json в список посылок в txt через importjson

2024-12-24 06:56 UTC, Fixey requested changes

2024-12-24 06:56 UTC, Fixey commented on build.gradle
>      implementation 'org.apache.commons:commons-collections4:4.4'
Версии надо вынести. Структурироватьь зависимости. Вначале имплементация потом тесты

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +            log.error("Структура Json некорректа!");
некорректна

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +        if (EXIT_COMMAND.equalsIgnoreCase(command)) {
С 33строчки по 43 по сути  это все одна логика по распарсиванию команды. Вынеси это в отедльный сервис который будет заниматься распарсиванием команды.

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +        if (command.startsWith("import ") || command.startsWith("save ") || command.startsWith("importjson ")) {
Сделай не через стрингу а через ENUM в которой будут список команд. 
это все выглядит что это валидация должна быть внутри parse command. и если что выкидывался через throw ошибка.

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +        if (command.startsWith("importjson ")) {
Сделай выбор команды через паттерн фабрика. 
По сути тебе в начале надо сделать обработчки строки. От туда ты можешь например выкинуть объект с параметрами команды.
Затем ты можешь работая с этим объектов по названию команды через фабрику дернуть ту реализацию которую тебе нужна

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +                fileProcessingService.processFile(path, useEasyAlgorithm, saveToFile, maxTrucks, useEvenAlgorithm);
Когда много входных переменных - значит уже что-то нето
Сделай просто чтобы на вход шел объект с параметрами нужными

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
> +            return fileReader.readAllLines(filePath);
fileReaderUtil должен быть статиком если он утилитарный

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
> +        try {
Сделай лучше try catch внутри fileReader.readAllLines так как это скорее этот метод должен эту ошибку выкидывать

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
> +        if (saveToFile) {
сделай фабрику чтобы легче было расширяться

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +        File outputDir = new File(OUTPUT_DIRECTORY);
вытащи в отдельный метод для создания файловой структуры

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +            Map<String, Object> truckMap = new LinkedHashMap<>(); //Linked чтобы вывод в json был по порядку
комментарии не нужны) но спасибо)

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +    public void saveToJson(List<Truck> trucks) {
я б порекомендовал возвращать json или  string который ты сохранил) Так проще тестами проверить, что сохранилось

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +        try {
вынеси в отедльный метод

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +            Map<String, Object> truckMap = new LinkedHashMap<>(); //Linked чтобы вывод в json был по порядку
Вынеси в отдельный метод

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +            for (Package pkg : truck.getPackages()) {
А не проще не через мапу а собрать объект, а потом объект представить в виде json? Тогда не будет лишних каких-то стрингов. И все будет крассиво.

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/JsonProcessingService.java
> +        for (Map<String, Object> truck : trucks) {
Вынеси в отдельный метод

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/util/FileSavingUtil.java
> +public class FileSavingUtil {
Если класс утилитарный - то это автоматически static

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
>      private final FileParserUtil fileParser;
FileParserUtil это не утилитарный класс а сервис. Сделай его пожалуйста сервисом и убери комментарии пожалуйста. Если код с комментариями - это значит что код написан плохо и непонятно раз его надо объяснять

2024-12-24 06:56 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/PackingService.java
> +                for (int startX = 0; startX <= truck.getWIDTH() - shape.getFirst().length(); startX++) { // Слева направо
Комментарий не нужен

2024-12-24 06:56 UTC, Fixey commented on src/test/java/org/hofftech/edu/service/FileProcessingServiceTest.java
> +        fileProcessingService.saveTrucksToFile(trucks);
Если ты поправишь что оно будет возврщатаь json или string ты сможешь проверить метод =)

2024-12-25 10:31 UTC, loveandpepper commented on src/main/java/org/hofftech/edu/util/FileSavingUtil.java
> +public class FileSavingUtil {
по идее в java нельзя верхнеуровневые (не вложенные) обозначать как статик? сделал утилиты final. либо можно тогда создать общий 1 класс и сделать их вложенными статиками?

2024-12-25 14:19 UTC, Fixey requested changes

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +        if (EXIT_COMMAND.equalsIgnoreCase(command)) {
Засунь это тоже в фабрику, это же команда.

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +                processor.process(command);
метод это всегда глагол. execute например

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/controller/CommandProcessorFactory.java
> +        processors.put(CommandType.IMPORT_JSON, new ImportJsonCommandProcessor(jsonProcessingService));
Очень классно придумано, никогда не думал о такой реализации. Единственное что, реалиации через hashmap ты всегда создаешь сущности. Сделай лучше через switch, чтобы было lazy инициализация

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/controller/processor/BaseFileCommandProcessor.java
> +package org.hofftech.edu.controller.processor;
это не должно быть в контролере это же сервисы

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/controller/processor/BaseFileCommandProcessor.java
> +        boolean useEasyAlgorithm = command.contains("easyalgorithm");
Ты парсишь внутри процесса который должен выполняться. Вынеси весь парсинг в отдельный метод и закинь его до вызова фабрики. Сформируй объект и кидай его дальше. Тут должна быть логика только исполнения

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/controller/processor/BaseFileCommandProcessor.java
> +        if (useEvenAlgorithm){
Тут тоже сделай фабрику. выбри алгоритм и вызови интерфейс

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/model/TruckDto.java
> +package org.hofftech.edu.model;
dto выносятся в отдельную папочку

2024-12-25 14:19 UTC, Fixey commented on src/main/java/org/hofftech/edu/controller/ConsoleController.java
>  import java.util.Scanner;
в контроллере должен быть только контроллер

2024-12-27 18:35 UTC, Fixey requested changes

2024-12-27 18:35 UTC, Fixey commented on src/main/java/org/hofftech/edu/handler/ConsoleCommandHandler.java
> +        CommandType commandType = CommandType.fromCommand(command);
Сделай номарльный класс в котором будет парситься вся твоя команда. И заполняться там и команд тайп и алгоритм и другие параметры. Сделай унифицированный класс.

2024-12-27 18:35 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
> +            FileSavingAlgorithm algorithm = savingAlgorithmFactory.getAlgorithm("json");
А зачем тебе тут фабрика?

2024-12-27 18:35 UTC, Fixey commented on src/main/java/org/hofftech/edu/service/FileProcessingService.java
> +        List<Truck> trucks = addPackages(useEasyAlgorithm, packages, maxTrucks, lazyAlg);
вот тут можно было выделить фабрику. Типо выбираешься имплементацию, и делаешь общий интерфейс.

2024-12-27 18:37 UTC, Fixey requested changes

2024-12-27 18:37 UTC, Fixey commented on src/test/java/org/hofftech/edu/service/FileProcessingServiceTest.java
> +        when(fileReader.readAllLines(filePath)).thenReturn(fileLines);
Такого метода нет

2024-12-29 21:16 UTC, Fixey approved these changes

2025-01-04 13:32 UTC, merged